/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemak;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author gonzc
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Inventario() {
       initComponents();
       Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
       int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
       int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
       this.setLocation(x, y);
       this.jLabel2.setText(" ");
       ImageIcon imagen = new ImageIcon("src/Imagenes/2.jpg");
       Icon icono = new ImageIcon(imagen.getImage().getScaledInstance( this.jLabel2.getWidth(),  this.jLabel2.getHeight(), Image.SCALE_DEFAULT));
       this.jLabel2.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fSButtonMD1 = new LIB.FSButtonMD();
        fSButtonMD2 = new LIB.FSButtonMD();
        Estilo = new javax.swing.JComboBox<>();
        Productos1 = new javax.swing.JComboBox<>();
        Color = new javax.swing.JComboBox<>();
        Tamaño1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fSButtonMD3 = new LIB.FSButtonMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("MiniLogo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 230, 70));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("INVENTARIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        fSButtonMD1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSButtonMD1.setText("X");
        fSButtonMD1.setColorHover(new java.awt.Color(153, 204, 255));
        fSButtonMD1.setColorNormal(new java.awt.Color(153, 204, 255));
        fSButtonMD1.setColorPressed(new java.awt.Color(102, 153, 255));
        fSButtonMD1.setColorTextNormal(new java.awt.Color(0, 0, 0));
        fSButtonMD1.setColorTextPressed(new java.awt.Color(0, 0, 0));
        fSButtonMD1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        fSButtonMD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD1ActionPerformed(evt);
            }
        });
        jPanel1.add(fSButtonMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 30));

        fSButtonMD2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSButtonMD2.setText("Seleccionar");
        fSButtonMD2.setColorHover(new java.awt.Color(153, 204, 255));
        fSButtonMD2.setColorNormal(new java.awt.Color(153, 204, 255));
        fSButtonMD2.setColorPressed(new java.awt.Color(102, 153, 255));
        fSButtonMD2.setColorTextNormal(new java.awt.Color(0, 0, 0));
        fSButtonMD2.setColorTextPressed(new java.awt.Color(0, 0, 0));
        fSButtonMD2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        fSButtonMD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD2ActionPerformed(evt);
            }
        });
        jPanel1.add(fSButtonMD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 120, 30));

        Estilo.setBackground(new java.awt.Color(153, 204, 255));
        Estilo.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar estilo" }));
        Estilo.setBorder(null);
        Estilo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstiloActionPerformed(evt);
            }
        });
        jPanel1.add(Estilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, -1));

        Productos1.setBackground(new java.awt.Color(153, 204, 255));
        Productos1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Productos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar producto" }));
        Productos1.setBorder(null);
        Productos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Productos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos1ActionPerformed(evt);
            }
        });
        jPanel1.add(Productos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        Color.setBackground(new java.awt.Color(153, 204, 255));
        Color.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar color" }));
        Color.setBorder(null);
        Color.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorActionPerformed(evt);
            }
        });
        jPanel1.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, -1));

        Tamaño1.setBackground(new java.awt.Color(153, 204, 255));
        Tamaño1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        Tamaño1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tamaño" }));
        Tamaño1.setBorder(null);
        Tamaño1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tamaño1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tamaño1ActionPerformed(evt);
            }
        });
        jPanel1.add(Tamaño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Especificaciones"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(153, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 430, 210));

        jLabel1.setText("Fotografia");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 430, 70));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel4.setText("Fotografía");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        fSButtonMD3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fSButtonMD3.setText("Buscar");
        fSButtonMD3.setColorHover(new java.awt.Color(153, 204, 255));
        fSButtonMD3.setColorNormal(new java.awt.Color(153, 204, 255));
        fSButtonMD3.setColorPressed(new java.awt.Color(102, 153, 255));
        fSButtonMD3.setColorTextNormal(new java.awt.Color(0, 0, 0));
        fSButtonMD3.setColorTextPressed(new java.awt.Color(0, 0, 0));
        fSButtonMD3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        fSButtonMD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSButtonMD3ActionPerformed(evt);
            }
        });
        jPanel1.add(fSButtonMD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fSButtonMD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fSButtonMD1ActionPerformed

    private void fSButtonMD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fSButtonMD2ActionPerformed

    private void Productos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Productos1ActionPerformed

    private void ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorActionPerformed

    private void Tamaño1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tamaño1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tamaño1ActionPerformed

    private void EstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstiloActionPerformed

    private void fSButtonMD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSButtonMD3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fSButtonMD3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JComboBox<String> Estilo;
    private javax.swing.JComboBox<String> Productos1;
    private javax.swing.JComboBox<String> Tamaño1;
    private LIB.FSButtonMD fSButtonMD1;
    private LIB.FSButtonMD fSButtonMD2;
    private LIB.FSButtonMD fSButtonMD3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
